### ISSUE TITLE
What Library

### ISSUE THREAD

**Issue by danbicks** [euphi/ESP-Touch#1]
Hi,

What "MPR121.h" library are you using for this project? can't seem to find it in your src folder.

Big thanks

Dans

**Comment by zerorist** [comment]
Hello
I'd be also glad to have this information, I can't find any functionnal MPR121 lib for esp8266.
Thank you for your answer

**Comment by euphi** [comment]
See https://github.com/BareConductive/mpr121

I just cloned it into the lib subdirectory. If you use platformio this is enough to compile my example code.

**Comment by euphi** [comment]
I forked the library to build with platformio, so you can use

```lib_deps=https://github.com/euphi/mpr121```

in platformio. 

See the branch https://github.com/euphi/ESP-Touch/tree/Display_WS2812 of ESP-Touch on how to use it.

Please note that my ESP-Touch project is not a library, it is used for some actual projects that are in "prototype" state and change often due to some new ideas.

The Display_WS2812 branch use of 8x8 WS2812 LED Matrix to show Time, temperature and a set temperature for a thermostat and can be controlled by touch.
